typography_spectrum: 0.03641788265667856
color:
  brandStrength: 0.5568885868415236
  lightness: 0.6423405422829092
  saturation: 0.43494633585214615
  rhythmicContrast: 0.08224127814173698
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.4732100395485759
name: Absolute Upholstery
description: We're not your average tradies.
